package com.example.storageservice.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee.proto

public final class EmployeeProto {
  private EmployeeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EmployeeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Employee)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string emp_id = 1;</code>
     * @return The empId.
     */
    java.lang.String getEmpId();
    /**
     * <code>string emp_id = 1;</code>
     * @return The bytes for empId.
     */
    com.google.protobuf.ByteString
        getEmpIdBytes();

    /**
     * <code>string emp_name = 2;</code>
     * @return The empName.
     */
    java.lang.String getEmpName();
    /**
     * <code>string emp_name = 2;</code>
     * @return The bytes for empName.
     */
    com.google.protobuf.ByteString
        getEmpNameBytes();

    /**
     * <code>.google.protobuf.Timestamp dob = 3;</code>
     * @return Whether the dob field is set.
     */
    boolean hasDob();
    /**
     * <code>.google.protobuf.Timestamp dob = 3;</code>
     * @return The dob.
     */
    com.google.protobuf.Timestamp getDob();
    /**
     * <code>.google.protobuf.Timestamp dob = 3;</code>
     */
    com.google.protobuf.TimestampOrBuilder getDobOrBuilder();

    /**
     * <code>double salary = 4;</code>
     * @return The salary.
     */
    double getSalary();

    /**
     * <code>int32 age = 5;</code>
     * @return The age.
     */
    int getAge();
  }
  /**
   * Protobuf type {@code Employee}
   */
  public static final class Employee extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Employee)
      EmployeeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Employee.newBuilder() to construct.
    private Employee(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Employee() {
      empId_ = "";
      empName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Employee();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Employee(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              empId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              empName_ = s;
              break;
            }
            case 26: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (dob_ != null) {
                subBuilder = dob_.toBuilder();
              }
              dob_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(dob_);
                dob_ = subBuilder.buildPartial();
              }

              break;
            }
            case 33: {

              salary_ = input.readDouble();
              break;
            }
            case 40: {

              age_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EmployeeProto.internal_static_Employee_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EmployeeProto.internal_static_Employee_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EmployeeProto.Employee.class, EmployeeProto.Employee.Builder.class);
    }

    public static final int EMP_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object empId_;
    /**
     * <code>string emp_id = 1;</code>
     * @return The empId.
     */
    @java.lang.Override
    public java.lang.String getEmpId() {
      java.lang.Object ref = empId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        empId_ = s;
        return s;
      }
    }
    /**
     * <code>string emp_id = 1;</code>
     * @return The bytes for empId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmpIdBytes() {
      java.lang.Object ref = empId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        empId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMP_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object empName_;
    /**
     * <code>string emp_name = 2;</code>
     * @return The empName.
     */
    @java.lang.Override
    public java.lang.String getEmpName() {
      java.lang.Object ref = empName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        empName_ = s;
        return s;
      }
    }
    /**
     * <code>string emp_name = 2;</code>
     * @return The bytes for empName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmpNameBytes() {
      java.lang.Object ref = empName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        empName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DOB_FIELD_NUMBER = 3;
    private com.google.protobuf.Timestamp dob_;
    /**
     * <code>.google.protobuf.Timestamp dob = 3;</code>
     * @return Whether the dob field is set.
     */
    @java.lang.Override
    public boolean hasDob() {
      return dob_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp dob = 3;</code>
     * @return The dob.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getDob() {
      return dob_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dob_;
    }
    /**
     * <code>.google.protobuf.Timestamp dob = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getDobOrBuilder() {
      return getDob();
    }

    public static final int SALARY_FIELD_NUMBER = 4;
    private double salary_;
    /**
     * <code>double salary = 4;</code>
     * @return The salary.
     */
    @java.lang.Override
    public double getSalary() {
      return salary_;
    }

    public static final int AGE_FIELD_NUMBER = 5;
    private int age_;
    /**
     * <code>int32 age = 5;</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getEmpIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, empId_);
      }
      if (!getEmpNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, empName_);
      }
      if (dob_ != null) {
        output.writeMessage(3, getDob());
      }
      if (salary_ != 0D) {
        output.writeDouble(4, salary_);
      }
      if (age_ != 0) {
        output.writeInt32(5, age_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getEmpIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, empId_);
      }
      if (!getEmpNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, empName_);
      }
      if (dob_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getDob());
      }
      if (salary_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, salary_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, age_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof EmployeeProto.Employee)) {
        return super.equals(obj);
      }
      EmployeeProto.Employee other = (EmployeeProto.Employee) obj;

      if (!getEmpId()
          .equals(other.getEmpId())) return false;
      if (!getEmpName()
          .equals(other.getEmpName())) return false;
      if (hasDob() != other.hasDob()) return false;
      if (hasDob()) {
        if (!getDob()
            .equals(other.getDob())) return false;
      }
      if (java.lang.Double.doubleToLongBits(getSalary())
          != java.lang.Double.doubleToLongBits(
              other.getSalary())) return false;
      if (getAge()
          != other.getAge()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EMP_ID_FIELD_NUMBER;
      hash = (53 * hash) + getEmpId().hashCode();
      hash = (37 * hash) + EMP_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getEmpName().hashCode();
      if (hasDob()) {
        hash = (37 * hash) + DOB_FIELD_NUMBER;
        hash = (53 * hash) + getDob().hashCode();
      }
      hash = (37 * hash) + SALARY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getSalary()));
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static EmployeeProto.Employee parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EmployeeProto.Employee parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EmployeeProto.Employee parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EmployeeProto.Employee parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EmployeeProto.Employee parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EmployeeProto.Employee parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EmployeeProto.Employee parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EmployeeProto.Employee parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static EmployeeProto.Employee parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static EmployeeProto.Employee parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static EmployeeProto.Employee parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EmployeeProto.Employee parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(EmployeeProto.Employee prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Employee}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Employee)
        EmployeeProto.EmployeeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EmployeeProto.internal_static_Employee_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EmployeeProto.internal_static_Employee_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EmployeeProto.Employee.class, EmployeeProto.Employee.Builder.class);
      }

      // Construct using EmployeeProto.Employee.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        empId_ = "";

        empName_ = "";

        if (dobBuilder_ == null) {
          dob_ = null;
        } else {
          dob_ = null;
          dobBuilder_ = null;
        }
        salary_ = 0D;

        age_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EmployeeProto.internal_static_Employee_descriptor;
      }

      @java.lang.Override
      public EmployeeProto.Employee getDefaultInstanceForType() {
        return EmployeeProto.Employee.getDefaultInstance();
      }

      @java.lang.Override
      public EmployeeProto.Employee build() {
        EmployeeProto.Employee result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public EmployeeProto.Employee buildPartial() {
        EmployeeProto.Employee result = new EmployeeProto.Employee(this);
        result.empId_ = empId_;
        result.empName_ = empName_;
        if (dobBuilder_ == null) {
          result.dob_ = dob_;
        } else {
          result.dob_ = dobBuilder_.build();
        }
        result.salary_ = salary_;
        result.age_ = age_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EmployeeProto.Employee) {
          return mergeFrom((EmployeeProto.Employee)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EmployeeProto.Employee other) {
        if (other == EmployeeProto.Employee.getDefaultInstance()) return this;
        if (!other.getEmpId().isEmpty()) {
          empId_ = other.empId_;
          onChanged();
        }
        if (!other.getEmpName().isEmpty()) {
          empName_ = other.empName_;
          onChanged();
        }
        if (other.hasDob()) {
          mergeDob(other.getDob());
        }
        if (other.getSalary() != 0D) {
          setSalary(other.getSalary());
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        EmployeeProto.Employee parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (EmployeeProto.Employee) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object empId_ = "";
      /**
       * <code>string emp_id = 1;</code>
       * @return The empId.
       */
      public java.lang.String getEmpId() {
        java.lang.Object ref = empId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          empId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string emp_id = 1;</code>
       * @return The bytes for empId.
       */
      public com.google.protobuf.ByteString
          getEmpIdBytes() {
        java.lang.Object ref = empId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          empId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string emp_id = 1;</code>
       * @param value The empId to set.
       * @return This builder for chaining.
       */
      public Builder setEmpId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        empId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string emp_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmpId() {
        
        empId_ = getDefaultInstance().getEmpId();
        onChanged();
        return this;
      }
      /**
       * <code>string emp_id = 1;</code>
       * @param value The bytes for empId to set.
       * @return This builder for chaining.
       */
      public Builder setEmpIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        empId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object empName_ = "";
      /**
       * <code>string emp_name = 2;</code>
       * @return The empName.
       */
      public java.lang.String getEmpName() {
        java.lang.Object ref = empName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          empName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string emp_name = 2;</code>
       * @return The bytes for empName.
       */
      public com.google.protobuf.ByteString
          getEmpNameBytes() {
        java.lang.Object ref = empName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          empName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string emp_name = 2;</code>
       * @param value The empName to set.
       * @return This builder for chaining.
       */
      public Builder setEmpName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        empName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string emp_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmpName() {
        
        empName_ = getDefaultInstance().getEmpName();
        onChanged();
        return this;
      }
      /**
       * <code>string emp_name = 2;</code>
       * @param value The bytes for empName to set.
       * @return This builder for chaining.
       */
      public Builder setEmpNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        empName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp dob_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dobBuilder_;
      /**
       * <code>.google.protobuf.Timestamp dob = 3;</code>
       * @return Whether the dob field is set.
       */
      public boolean hasDob() {
        return dobBuilder_ != null || dob_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp dob = 3;</code>
       * @return The dob.
       */
      public com.google.protobuf.Timestamp getDob() {
        if (dobBuilder_ == null) {
          return dob_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dob_;
        } else {
          return dobBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp dob = 3;</code>
       */
      public Builder setDob(com.google.protobuf.Timestamp value) {
        if (dobBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dob_ = value;
          onChanged();
        } else {
          dobBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dob = 3;</code>
       */
      public Builder setDob(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (dobBuilder_ == null) {
          dob_ = builderForValue.build();
          onChanged();
        } else {
          dobBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dob = 3;</code>
       */
      public Builder mergeDob(com.google.protobuf.Timestamp value) {
        if (dobBuilder_ == null) {
          if (dob_ != null) {
            dob_ =
              com.google.protobuf.Timestamp.newBuilder(dob_).mergeFrom(value).buildPartial();
          } else {
            dob_ = value;
          }
          onChanged();
        } else {
          dobBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dob = 3;</code>
       */
      public Builder clearDob() {
        if (dobBuilder_ == null) {
          dob_ = null;
          onChanged();
        } else {
          dob_ = null;
          dobBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dob = 3;</code>
       */
      public com.google.protobuf.Timestamp.Builder getDobBuilder() {
        
        onChanged();
        return getDobFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp dob = 3;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getDobOrBuilder() {
        if (dobBuilder_ != null) {
          return dobBuilder_.getMessageOrBuilder();
        } else {
          return dob_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : dob_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp dob = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getDobFieldBuilder() {
        if (dobBuilder_ == null) {
          dobBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getDob(),
                  getParentForChildren(),
                  isClean());
          dob_ = null;
        }
        return dobBuilder_;
      }

      private double salary_ ;
      /**
       * <code>double salary = 4;</code>
       * @return The salary.
       */
      @java.lang.Override
      public double getSalary() {
        return salary_;
      }
      /**
       * <code>double salary = 4;</code>
       * @param value The salary to set.
       * @return This builder for chaining.
       */
      public Builder setSalary(double value) {
        
        salary_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double salary = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSalary() {
        
        salary_ = 0D;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 5;</code>
       * @return The age.
       */
      @java.lang.Override
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 5;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Employee)
    }

    // @@protoc_insertion_point(class_scope:Employee)
    private static final EmployeeProto.Employee DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new EmployeeProto.Employee();
    }

    public static EmployeeProto.Employee getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Employee>
        PARSER = new com.google.protobuf.AbstractParser<Employee>() {
      @java.lang.Override
      public Employee parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Employee(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Employee> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Employee> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public EmployeeProto.Employee getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Employee_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Employee_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016employee.proto\032\037google/protobuf/timest" +
      "amp.proto\"r\n\010Employee\022\016\n\006emp_id\030\001 \001(\t\022\020\n" +
      "\010emp_name\030\002 \001(\t\022\'\n\003dob\030\003 \001(\0132\032.google.pr" +
      "otobuf.Timestamp\022\016\n\006salary\030\004 \001(\001\022\013\n\003age\030" +
      "\005 \001(\005B\017B\rEmployeeProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_Employee_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Employee_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Employee_descriptor,
        new java.lang.String[] { "EmpId", "EmpName", "Dob", "Salary", "Age", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
